/**
 * Enterprise Admin Navigation Registry
 * Config-driven, role-aware, hierarchical navigation definition
 */

export const ADMIN_NAV_GROUPS = {
  OVERVIEW: 'overview',
  CATALOG: 'catalog',
  SALES: 'sales',
  PURCHASES: 'purchases',
  SUPPLIERS: 'suppliers',
  INVENTORY: 'inventory',
  FINANCE: 'finance',
  PROMOTIONS: 'promotions',
  MARKETING: 'marketing',
  STOREFRONT: 'storefront',
  CX: 'customer_experience',
  OPERATIONS: 'operations',
  CCTV: 'cctv',
  REPORTING: 'reporting',
  INTEGRATIONS: 'integrations',
  SYSTEM: 'system',
};

export const ADMIN_NAV_ITEMS = [
  // ==========================================
  // 1. OVERVIEW
  // ==========================================
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: 'LayoutDashboard',
    route: '/admin',
    group: ADMIN_NAV_GROUPS.OVERVIEW,
    permission: 'dashboard.view',
    order: 10,
    description: 'Executive sales, orders, and real-time business telemetry',
  },
  {
    id: 'sales_overview',
    label: 'Sales & Revenue',
    icon: 'BarChart3',
    route: '/admin/reports/sales',
    group: ADMIN_NAV_GROUPS.OVERVIEW,
    permission: 'reports.sales',
    order: 20,
    description: 'Financial velocity, payment distribution, and revenue trends',
  },
  {
    id: 'operations_overview',
    label: 'Operations & Pipeline',
    icon: 'Activity',
    route: '/admin/reports/operations',
    group: ADMIN_NAV_GROUPS.OVERVIEW,
    permission: 'reports.operations',
    order: 30,
    description: 'Order fulfillment pipeline, dispatch speed, and bottleneck alerts',
  },

  // ==========================================
  // 2. CATALOG
  // ==========================================
  {
    id: 'products',
    label: 'Products',
    icon: 'Package',
    route: '/admin/products',
    group: ADMIN_NAV_GROUPS.CATALOG,
    permission: 'products.manage',
    badge: 'Catalog',
    order: 100,
    description: 'Hardware product inventory, pricing, specifications, and SEO',
  },
  {
    id: 'categories',
    label: 'Categories',
    icon: 'FolderTree',
    route: '/admin/categories',
    group: ADMIN_NAV_GROUPS.CATALOG,
    permission: 'categories.manage',
    order: 110,
    description: 'Multi-level category taxonomy, SEO slugs, and banner mappings',
  },
  {
    id: 'brands',
    label: 'Brands',
    icon: 'Tag',
    route: '/admin/brands',
    group: ADMIN_NAV_GROUPS.CATALOG,
    permission: 'brands.manage',
    order: 120,
    description: 'Authorized manufacturers, vendor logos, and brand landing pages',
  },
  {
    id: 'specifications',
    label: 'Attributes & Specs',
    icon: 'Layers',
    route: '/admin/specifications',
    group: ADMIN_NAV_GROUPS.CATALOG,
    permission: 'specifications.manage',
    order: 130,
    description: 'Dynamic PC builder specification attributes and technical matrix',
  },
  {
    id: 'media_library',
    label: 'Media Library',
    icon: 'Image',
    route: '/admin/media',
    group: ADMIN_NAV_GROUPS.CATALOG,
    permission: 'media.manage',
    badge: 'Central',
    order: 140,
    description: 'Centralized digital asset manager, CDN image optimizer, and folders',
  },
  {
    id: 'units',
    label: 'Units',
    icon: 'Ruler',
    route: '/admin/units',
    group: ADMIN_NAV_GROUPS.CATALOG,
    permission: 'units.manage',
    order: 145,
    description: 'Measurement units, short codes, symbols, and unit conversions',
  },
  {
    id: 'data_management',
    label: 'Bulk Import / Export',
    icon: 'ArrowUpDown',
    route: '/admin/data-management',
    group: ADMIN_NAV_GROUPS.CATALOG,
    permission: 'bulk.import',
    badge: 'Enterprise',
    order: 150,
    description: 'Bulk CSV & Excel data import wizard, export studio, and audit logs',
    children: [
      {
        id: 'data_import_wizard',
        label: 'Import Wizard',
        route: '/admin/data-management/import',
        icon: 'UploadCloud',
      },
      {
        id: 'data_export_studio',
        label: 'Export Studio',
        route: '/admin/data-management/export',
        icon: 'DownloadCloud',
      },
      {
        id: 'data_history_logs',
        label: 'History & Logs',
        route: '/admin/data-management/history',
        icon: 'History',
      },
    ],
  },

  // ==========================================
  // 3. OPERATIONS & POS
  // ==========================================
  {
    id: 'pos_terminal',
    label: 'POS Terminal',
    icon: 'Store',
    route: '/admin/pos',
    group: ADMIN_NAV_GROUPS.OPERATIONS,
    permission: 'pos.view',
    badge: 'Live POS',
    order: 190,
    description: 'Fast barcode cashier terminal, split payments, instant thermal receipt',
  },
  {
    id: 'sales_orders',
    label: 'Sales Operations',
    icon: 'Receipt',
    route: '/admin/sales',
    group: ADMIN_NAV_GROUPS.SALES,
    permission: 'sales.view',
    order: 195,
    description: 'Commercial sales orders, walk-in invoices, and customer returns',
  },
  {
    id: 'orders',
    label: 'Ecommerce Orders',
    icon: 'ShoppingBag',
    route: '/admin/orders',
    group: ADMIN_NAV_GROUPS.SALES,
    permission: 'orders.manage',
    order: 200,
    description: 'Online store checkouts, courier dispatch, invoices, and refunds',
  },
  {
    id: 'purchases',
    label: 'Purchases & Receiving',
    icon: 'PackagePlus',
    route: '/admin/purchases',
    group: ADMIN_NAV_GROUPS.PURCHASES,
    permission: 'purchases.view',
    order: 220,
    description: 'Supplier purchase orders, partial goods receiving, and vendor bills',
  },
  {
    id: 'suppliers',
    label: 'Suppliers Directory',
    icon: 'Building2',
    route: '/admin/suppliers',
    group: ADMIN_NAV_GROUPS.SUPPLIERS,
    permission: 'suppliers.view',
    order: 230,
    description: 'Hardware vendors, distributors, payable balances, and contact book',
  },
  {
    id: 'abandoned_carts',
    label: 'Abandoned Carts',
    icon: 'RefreshCw',
    route: '/admin/abandoned-carts',
    group: ADMIN_NAV_GROUPS.SALES,
    permission: 'marketing.manage',
    badge: 'Recovery',
    order: 240,
    description: 'Uncompleted customer checkouts and automated recovery funnels',
  },

  // ==========================================
  // 4. INVENTORY & WAREHOUSES
  // ==========================================
  {
    id: 'inventory_overview',
    label: 'Inventory Overview',
    icon: 'Boxes',
    route: '/admin/inventory',
    group: ADMIN_NAV_GROUPS.INVENTORY,
    permission: 'inventory.view',
    order: 400,
    description: 'Stock valuation, audit movements, reason adjustments, and stock levels',
  },
  {
    id: 'stock_transfers',
    label: 'Stock Transfers',
    icon: 'ArrowLeftRight',
    route: '/admin/inventory/transfers',
    group: ADMIN_NAV_GROUPS.INVENTORY,
    permission: 'inventory.transfer',
    order: 405,
    description: 'Inter-warehouse transfers, in-transit manifests, and dispatch verification',
  },
  {
    id: 'stock_counts',
    label: 'Stock Counts & Audits',
    icon: 'ClipboardCheck',
    route: '/admin/inventory/counts',
    group: ADMIN_NAV_GROUPS.INVENTORY,
    permission: 'inventory.count',
    order: 410,
    description: 'Physical inventory cycle counting sheets and variance approval',
  },
  {
    id: 'warehouses',
    label: 'Warehouses',
    icon: 'Warehouse',
    route: '/admin/warehouses',
    group: ADMIN_NAV_GROUPS.INVENTORY,
    permission: 'inventory.view',
    order: 415,
    description: 'Multi-location warehouse facilities, managers, and rack zones',
  },

  // ==========================================
  // 5. FINANCE & DOUBLE-ENTRY ACCOUNTS
  // ==========================================
  {
    id: 'accounts_dashboard',
    label: 'Finance Dashboard',
    icon: 'Landmark',
    route: '/admin/accounts',
    group: ADMIN_NAV_GROUPS.FINANCE,
    permission: 'accounts.view',
    badge: 'ERP',
    order: 450,
    description: 'Cash flow velocity, revenue vs purchases, net profit, and liquid assets',
  },
  {
    id: 'chart_of_accounts',
    label: 'Chart of Accounts',
    icon: 'Network',
    route: '/admin/accounts/chart-of-accounts',
    group: ADMIN_NAV_GROUPS.FINANCE,
    permission: 'accounts.manage_accounts',
    order: 455,
    description: '5-category standard ledger hierarchy (Assets, Liabilities, Equity, Income, Expense)',
  },
  {
    id: 'general_ledger',
    label: 'Transactions Journal',
    icon: 'FileText',
    route: '/admin/accounts/transactions',
    group: ADMIN_NAV_GROUPS.FINANCE,
    permission: 'accounts.view',
    order: 460,
    description: 'Double-entry balanced transaction ledger and audit trace',
  },
  {
    id: 'expenses',
    label: 'Expense Vouchers',
    icon: 'ArrowUpRight',
    route: '/admin/accounts/expenses',
    group: ADMIN_NAV_GROUPS.FINANCE,
    permission: 'accounts.manage_expenses',
    order: 465,
    description: 'Operating expenses, utility bills, office costs, and payment registers',
  },
  {
    id: 'income',
    label: 'Income Vouchers',
    icon: 'ArrowDownLeft',
    route: '/admin/accounts/income',
    group: ADMIN_NAV_GROUPS.FINANCE,
    permission: 'accounts.manage_income',
    order: 470,
    description: 'Miscellaneous income, interest, and non-retail business receipts',
  },
  {
    id: 'receivables',
    label: 'Accounts Receivable',
    icon: 'BadgeDollarSign',
    route: '/admin/accounts/receivables',
    group: ADMIN_NAV_GROUPS.FINANCE,
    permission: 'accounts.view',
    order: 475,
    description: 'Customer credit ledger, overdue invoices, and payment collections',
  },
  {
    id: 'payables',
    label: 'Accounts Payable',
    icon: 'CreditCard',
    route: '/admin/accounts/payables',
    group: ADMIN_NAV_GROUPS.FINANCE,
    permission: 'accounts.view',
    order: 480,
    description: 'Supplier dues, purchase bill obligations, and payment releases',
  },
  {
    id: 'cash_bank',
    label: 'Cash & Bank Registers',
    icon: 'Wallet',
    route: '/admin/accounts/cash-bank',
    group: ADMIN_NAV_GROUPS.FINANCE,
    permission: 'accounts.view',
    order: 485,
    description: 'Cash drawer vaults, BRAC/DBBL bank accounts, and bKash/Nagad balances',
  },

  // ==========================================
  // 4. CUSTOMERS
  // ==========================================
  {
    id: 'customers',
    label: 'Customers',
    icon: 'Users',
    route: '/admin/customers',
    group: ADMIN_NAV_GROUPS.CUSTOMERS,
    permission: 'customers.manage',
    order: 300,
    description: 'Customer profiles, lifetime value, addresses, and purchasing telemetry',
  },
  {
    id: 'fraud_checker',
    label: 'Fraud Checker',
    icon: 'ShieldAlert',
    route: '/admin/customers/fraud-checker',
    group: ADMIN_NAV_GROUPS.CUSTOMERS,
    permission: 'fraud.manage',
    badge: 'AI Shield',
    order: 310,
    description: 'Courier cancellation history, blacklist phone/IP, and risk scoring',
  },
  {
    id: 'fraud_reviews',
    label: 'Fraud Review Queue',
    icon: 'ShieldCheck',
    route: '/admin/customers/fraud-reviews',
    group: ADMIN_NAV_GROUPS.CUSTOMERS,
    permission: 'fraud.manage',
    order: 320,
    description: 'High-risk flagged orders pending manual audit approval',
  },

  // ==========================================
  // 5. INVENTORY
  // ==========================================
  {
    id: 'inventory_ledger',
    label: 'Inventory Ledger',
    icon: 'Warehouse',
    route: '/admin/inventory',
    group: ADMIN_NAV_GROUPS.INVENTORY,
    permission: 'inventory.manage',
    order: 400,
    description: 'Stock valuation, audit movements, adjustments, and warehouse ledger',
  },
  {
    id: 'low_stock_report',
    label: 'Stock Intelligence',
    icon: 'Boxes',
    route: '/admin/reports/inventory',
    group: ADMIN_NAV_GROUPS.INVENTORY,
    permission: 'inventory.manage',
    order: 410,
    description: 'Stock turnover velocity, reorder thresholds, and depletion analysis',
  },

  // ==========================================
  // 6. PRICING & PROMOTIONS
  // ==========================================
  {
    id: 'coupons',
    label: 'Coupons & Vouchers',
    icon: 'Ticket',
    route: '/admin/coupons',
    group: ADMIN_NAV_GROUPS.PROMOTIONS,
    permission: 'promotions.manage',
    order: 500,
    description: 'Discount promo codes, minimum basket limits, and usage caps',
  },
  {
    id: 'flash_sales',
    label: 'Flash Sales',
    icon: 'Flame',
    route: '/admin/flash-sales',
    group: ADMIN_NAV_GROUPS.PROMOTIONS,
    permission: 'promotions.manage',
    badge: 'Hot',
    order: 510,
    description: 'Time-limited flash deals, countdown tickers, and stock reservations',
  },
  {
    id: 'offers',
    label: 'Campaign Offers',
    icon: 'Tag',
    route: '/admin/offers',
    group: ADMIN_NAV_GROUPS.PROMOTIONS,
    permission: 'promotions.manage',
    order: 520,
    description: 'Bundle promotions, holiday special deals, and seasonal campaigns',
  },
  {
    id: 'emi_partners',
    label: 'EMI Financing',
    icon: 'CreditCard',
    route: '/admin/emi-partners',
    group: ADMIN_NAV_GROUPS.PROMOTIONS,
    permission: 'settings.manage',
    order: 530,
    description: 'Bank partner tenures, 0% interest terms, and calculation matrices',
  },

  // ==========================================
  // 7. MARKETING & AUTOMATIONS
  // ==========================================
  {
    id: 'landing_pages',
    label: 'Landing Page Hub',
    icon: 'Sparkles',
    route: '/admin/marketing/landing-pages',
    group: ADMIN_NAV_GROUPS.MARKETING,
    permission: 'marketing.manage',
    badge: 'Meta Ads',
    order: 600,
    description: 'High-converting landing page builder for Meta & Google ad campaigns',
  },
  {
    id: 'marketing_automations',
    label: 'Automated Journeys',
    icon: 'Mail',
    route: '/admin/marketing-automations',
    group: ADMIN_NAV_GROUPS.MARKETING,
    permission: 'marketing.manage',
    order: 610,
    description: 'Lifecycle email/SMS sequences, welcome journeys, and win-backs',
  },
  {
    id: 'product_feeds',
    label: 'Product Feeds',
    icon: 'Share2',
    route: '/admin/marketing/feeds',
    group: ADMIN_NAV_GROUPS.MARKETING,
    permission: 'marketing.manage',
    order: 620,
    description: 'Automated XML/CSV sync for Meta Catalog & Google Merchant Center',
  },
  {
    id: 'email_dashboard',
    label: 'Email Campaigns',
    icon: 'Send',
    route: '/admin/communication/email-dashboard',
    group: ADMIN_NAV_GROUPS.MARKETING,
    permission: 'marketing.manage',
    order: 630,
    description: 'Broadcast email campaigns, visual builder, and open/click telemetry',
  },
  {
    id: 'sms_dashboard',
    label: 'SMS Broadcasting',
    icon: 'MessageSquare',
    route: '/admin/communication/sms-dashboard',
    group: ADMIN_NAV_GROUPS.MARKETING,
    permission: 'marketing.manage',
    order: 640,
    description: 'Bulk SMS campaigns, Bangladeshi gateway delivery, and template tags',
  },

  // ==========================================
  // 8. STOREFRONT MANAGEMENT
  // ==========================================
  {
    id: 'storefront_appearance',
    label: 'Storefront Themes',
    icon: 'Store',
    route: '/admin/settings?tab=storefront',
    group: ADMIN_NAV_GROUPS.STOREFRONT,
    permission: 'storefront.manage',
    badge: 'v1/v2/v3',
    order: 700,
    description: 'Version switcher (Classic v1, Modern v2, Gadget Hub v3), preview, and themes',
  },
  {
    id: 'header_footer',
    label: 'Header & Footer Builder',
    icon: 'Sliders',
    route: '/admin/header-footer',
    group: ADMIN_NAV_GROUPS.STOREFRONT,
    permission: 'storefront.manage',
    badge: 'Dynamic',
    order: 710,
    description: 'Live topbar notice ticker, logo branding, footer columns, and hotlines',
  },
  {
    id: 'homepage_builder',
    label: 'Homepage Sections',
    icon: 'Sliders',
    route: '/admin/homepage',
    group: ADMIN_NAV_GROUPS.STOREFRONT,
    permission: 'storefront.manage',
    order: 720,
    description: 'Drag-and-drop section sorter, featured grids, and quick category pills',
  },
  {
    id: 'navigation_menus',
    label: 'Navigation & Mega Menu',
    icon: 'Menu',
    route: '/admin/navigation',
    group: ADMIN_NAV_GROUPS.STOREFRONT,
    permission: 'storefront.manage',
    order: 730,
    description: 'Header mega menu layout, featured category chips, and custom links',
  },
  {
    id: 'banners',
    label: 'Promo Banners',
    icon: 'Image',
    route: '/admin/banners',
    group: ADMIN_NAV_GROUPS.STOREFRONT,
    permission: 'storefront.manage',
    order: 740,
    description: 'Hero slider banners, sidebar callouts, and seasonal promotion strips',
  },
  {
    id: 'cms_pages',
    label: 'Policy & CMS Pages',
    icon: 'FileText',
    route: '/admin/pages',
    group: ADMIN_NAV_GROUPS.STOREFRONT,
    permission: 'storefront.manage',
    order: 750,
    description: 'Warranty terms, privacy policy, refund guidelines, and custom pages',
  },
  {
    id: 'blog_posts',
    label: 'Blog & Articles',
    icon: 'BookOpen',
    route: '/admin/blog',
    group: ADMIN_NAV_GROUPS.STOREFRONT,
    permission: 'storefront.manage',
    order: 760,
    description: 'Tech guides, product reviews, unboxing articles, and SEO blog posts',
  },

  // ==========================================
  // 9. CUSTOMER EXPERIENCE & SUPPORT
  // ==========================================
  {
    id: 'product_reviews',
    label: 'Product Reviews',
    icon: 'Star',
    route: '/admin/reviews',
    group: ADMIN_NAV_GROUPS.CX,
    permission: 'reviews.manage',
    order: 800,
    description: 'Moderation queue, verified purchase ratings, and customer media photos',
  },
  {
    id: 'support_tickets',
    label: 'Support Tickets',
    icon: 'LifeBuoy',
    route: '/admin/support-tickets',
    group: ADMIN_NAV_GROUPS.CX,
    permission: 'support.manage',
    order: 810,
    description: 'AI chatbot escalations, customer complaint inbox, and SLA tracking',
  },
  {
    id: 'service_warranty',
    label: 'Repair & Servicing',
    icon: 'Wrench',
    route: '/admin/service-requests',
    group: ADMIN_NAV_GROUPS.CX,
    permission: 'service.manage',
    order: 820,
    description: 'Hardware RMA tickets, service center drop-offs, and warranty claims',
  },
  {
    id: 'presales_questions',
    label: 'Q&A Inquiries',
    icon: 'HelpCircle',
    route: '/admin/questions',
    group: ADMIN_NAV_GROUPS.CX,
    permission: 'questions.manage',
    order: 830,
    description: 'Customer pre-sales questions on product pages with verified answers',
  },

  // ==========================================
  // 10. OPERATIONS & LOGISTICS
  // ==========================================
  {
    id: 'shipments',
    label: 'Shipments & Dispatch',
    icon: 'Truck',
    route: '/admin/shipments',
    group: ADMIN_NAV_GROUPS.OPERATIONS,
    permission: 'orders.manage',
    badge: 'Live',
    order: 900,
    description: 'One-click Steadfast & Pathao courier booking, waybills, and live tracking',
  },
  {
    id: 'payments',
    label: 'Payment Verifications',
    icon: 'CreditCard',
    route: '/admin/payments',
    group: ADMIN_NAV_GROUPS.OPERATIONS,
    permission: 'payments.manage',
    order: 910,
    description: 'Manual bKash/Nagad TrxID audits, bank slip approvals, and POS verification',
  },

  // ==========================================
  // 11. CCTV & SURVEILLANCE SOLUTIONS (1ST CLASS)
  // ==========================================
  {
    id: 'cctv_dashboard',
    label: 'CCTV Dashboard',
    icon: 'ShieldCheck',
    route: '/admin/cctv',
    group: ADMIN_NAV_GROUPS.CCTV,
    permission: 'cctv.manage',
    badge: 'v2.4',
    order: 1000,
    description: 'Estimator metrics, active commercial quotes, and installation health',
  },
  {
    id: 'cctv_analytics',
    label: 'CCTV Intelligence & BI',
    icon: 'TrendingUp',
    route: '/admin/cctv/analytics',
    group: ADMIN_NAV_GROUPS.CCTV,
    permission: 'cctv.manage',
    badge: 'BI',
    order: 1010,
    description: 'System conversion funnel, storage calculation insights, and brand mix',
  },
  {
    id: 'cctv_projects',
    label: 'Enterprise Projects',
    icon: 'Layers',
    route: '/admin/cctv/projects',
    group: ADMIN_NAV_GROUPS.CCTV,
    permission: 'cctv.manage',
    badge: 'Multi-Site',
    order: 1020,
    description: 'Corporate multi-site deployments, campus buildings, and floor plans',
  },
  {
    id: 'cctv_service_center',
    label: 'Service Center Hub',
    icon: 'Wrench',
    route: '/admin/cctv/service-center',
    group: ADMIN_NAV_GROUPS.CCTV,
    permission: 'cctv.manage',
    order: 1030,
    description: 'Technician dispatch queue, maintenance tickets, and service SLA',
  },
  {
    id: 'cctv_service_requests',
    label: 'Service Tickets',
    icon: 'LifeBuoy',
    route: '/admin/cctv/service-requests',
    group: ADMIN_NAV_GROUPS.CCTV,
    permission: 'cctv.manage',
    order: 1040,
    description: 'CCTV system fault repairs, on-site diagnostics, and preventive visits',
  },
  {
    id: 'cctv_installed_equipment',
    label: 'Installed Equipment',
    icon: 'Video',
    route: '/admin/cctv/installed-equipment',
    group: ADMIN_NAV_GROUPS.CCTV,
    permission: 'cctv.manage',
    order: 1050,
    description: 'Camera serial numbers, IP address registries, and active warranties',
  },
  {
    id: 'cctv_surveys',
    label: 'Site Surveys',
    icon: 'MapPin',
    route: '/admin/cctv/surveys',
    group: ADMIN_NAV_GROUPS.CCTV,
    permission: 'cctv.manage',
    order: 1060,
    description: 'Engineering site feasibility assessments, field reports, and cable maps',
  },
  {
    id: 'cctv_installations',
    label: 'Installation Jobs',
    icon: 'Wrench',
    route: '/admin/cctv/installations',
    group: ADMIN_NAV_GROUPS.CCTV,
    permission: 'cctv.manage',
    order: 1070,
    description: 'On-site installation workflows, commissioning tests, and completion sign-offs',
  },
  {
    id: 'cctv_services_rates',
    label: 'Service Rates & Types',
    icon: 'DollarSign',
    route: '/admin/cctv/services',
    group: ADMIN_NAV_GROUPS.CCTV,
    permission: 'cctv.manage',
    order: 1080,
    description: 'Per-camera installation charges, AMC contracts, and labor tariffs',
  },
  {
    id: 'cctv_profiles',
    label: 'Hardware Profiles',
    icon: 'Package',
    route: '/admin/cctv/profiles',
    group: ADMIN_NAV_GROUPS.CCTV,
    permission: 'cctv.manage',
    order: 1090,
    description: 'Camera form factors, IR distance, PoE specs, and NVR channel capacities',
  },
  {
    id: 'cctv_rules',
    label: 'Rule Engine',
    icon: 'Sliders',
    route: '/admin/cctv/rules',
    group: ADMIN_NAV_GROUPS.CCTV,
    permission: 'cctv.manage',
    order: 1100,
    description: 'Compatibility matrices, storage calculation algorithms, and recommendation rules',
  },
  {
    id: 'cctv_estimates',
    label: 'Project Estimates',
    icon: 'FileText',
    route: '/admin/cctv/estimates',
    group: ADMIN_NAV_GROUPS.CCTV,
    permission: 'cctv.manage',
    order: 1110,
    description: 'Generated equipment bills of materials, bandwidth, and storage sizing',
  },
  {
    id: 'cctv_quotes',
    label: 'Commercial Quotations',
    icon: 'Tag',
    route: '/admin/cctv/quotes',
    group: ADMIN_NAV_GROUPS.CCTV,
    permission: 'cctv.manage',
    order: 1120,
    description: 'Formal PDF quotations, customer approval links, and conversion to orders',
  },
  {
    id: 'cctv_reports',
    label: 'Custom BI Reports',
    icon: 'BarChart3',
    route: '/admin/cctv/reports',
    group: ADMIN_NAV_GROUPS.CCTV,
    permission: 'cctv.manage',
    order: 1130,
    description: 'Custom CCTV report builder with multi-metric cross-tabulation',
  },
  {
    id: 'cctv_alerts',
    label: 'CCTV Alert Center',
    icon: 'AlertTriangle',
    route: '/admin/cctv/alerts',
    group: ADMIN_NAV_GROUPS.CCTV,
    permission: 'cctv.manage',
    order: 1140,
    description: 'Warranty expirations, unassigned installation alerts, and survey backlog',
  },
  {
    id: 'cctv_tester',
    label: 'Live Rule Tester',
    icon: 'Sparkles',
    route: '/admin/cctv/test',
    group: ADMIN_NAV_GROUPS.CCTV,
    permission: 'cctv.manage',
    badge: 'Live',
    order: 1150,
    description: 'Interactive diagnostic tool to test calculations against real engine code',
  },
  {
    id: 'cctv_settings',
    label: 'Engine Settings',
    icon: 'Cpu',
    route: '/admin/cctv/settings',
    group: ADMIN_NAV_GROUPS.CCTV,
    permission: 'cctv.manage',
    order: 1160,
    description: 'Storage overhead %, cable waste safety margin, and default retention parameters',
  },

  // ==========================================
  // 12. REPORTING & INTELLIGENCE
  // ==========================================
  {
    id: 'reports_executive',
    label: 'Intelligence Center',
    icon: 'BarChart3',
    route: '/admin/reports',
    group: ADMIN_NAV_GROUPS.REPORTING,
    permission: 'reports.view',
    order: 1200,
    description: 'Unified cross-module intelligence hub and scheduled export reports',
  },
  {
    id: 'reports_sales',
    label: 'Sales & Revenue',
    icon: 'TrendingUp',
    route: '/admin/reports/sales',
    group: ADMIN_NAV_GROUPS.REPORTING,
    permission: 'reports.sales',
    order: 1210,
    description: 'Sales velocity, payment methods, order status distributions, and revenue',
  },
  {
    id: 'reports_products',
    label: 'Product Intelligence',
    icon: 'Package',
    route: '/admin/reports/products',
    group: ADMIN_NAV_GROUPS.REPORTING,
    permission: 'reports.products',
    order: 1220,
    description: 'Best-selling hardware, zero sales deadstock, and brand revenue breakdown',
  },
  {
    id: 'reports_inventory',
    label: 'Inventory Valuation',
    icon: 'Warehouse',
    route: '/admin/reports/inventory',
    group: ADMIN_NAV_GROUPS.REPORTING,
    permission: 'reports.inventory',
    order: 1230,
    description: 'Retail vs cost inventory valuation, margin projection, and fast/slow movers',
  },
  {
    id: 'reports_customers',
    label: 'Customer Intelligence',
    icon: 'Users',
    route: '/admin/reports/customers',
    group: ADMIN_NAV_GROUPS.REPORTING,
    permission: 'reports.customers',
    order: 1240,
    description: 'Repeat purchase rates, top spending VIP customers, and loyalty points',
  },

  // ==========================================
  // 13. INTEGRATIONS & GATEWAYS
  // ==========================================
  {
    id: 'settings_courier',
    label: 'Courier APIs',
    icon: 'Truck',
    route: '/admin/settings/courier',
    group: ADMIN_NAV_GROUPS.INTEGRATIONS,
    permission: 'settings.manage',
    badge: 'Steadfast/Pathao',
    order: 1300,
    description: 'Courier credentials, webhook listeners, and automatic status polling',
  },
  {
    id: 'settings_sms_gateways',
    label: 'SMS Gateways',
    icon: 'Radio',
    route: '/admin/settings/sms-gateways',
    group: ADMIN_NAV_GROUPS.INTEGRATIONS,
    permission: 'settings.manage',
    badge: 'BulkSMS/MIM',
    order: 1310,
    description: 'Bangladeshi SMS gateway endpoints, API keys, and balance check',
  },
  {
    id: 'settings_email_gateways',
    label: 'Email Gateways',
    icon: 'Mail',
    route: '/admin/settings/email',
    group: ADMIN_NAV_GROUPS.INTEGRATIONS,
    permission: 'settings.manage',
    badge: 'SMTP/API',
    order: 1320,
    description: 'SMTP relays, transactional email servers, and DNS health checks',
  },
  {
    id: 'settings_payment_methods',
    label: 'Payment Gateways',
    icon: 'CreditCard',
    route: '/admin/settings/payment-methods',
    group: ADMIN_NAV_GROUPS.INTEGRATIONS,
    permission: 'settings.manage',
    order: 1330,
    description: 'SSLCommerz, bKash, Nagad, Cash on Delivery, and POS configurations',
  },
  {
    id: 'settings_analytics',
    label: 'Tracking & Analytics',
    icon: 'TrendingUp',
    route: '/admin/settings/analytics',
    group: ADMIN_NAV_GROUPS.INTEGRATIONS,
    permission: 'settings.manage',
    order: 1340,
    description: 'Google Analytics 4, Meta Pixel, Conversions API, and TikTok tracking',
  },

  // ==========================================
  // 14. SYSTEM & SECURITY
  // ==========================================
  {
    id: 'system_users',
    label: 'Users & RBAC Roles',
    icon: 'UserCog',
    route: '/admin/users',
    group: ADMIN_NAV_GROUPS.SYSTEM,
    permission: 'users.manage',
    order: 1400,
    description: 'Admin staff accounts, granular role assignments, and permission control',
  },
  {
    id: 'notifications_center',
    label: 'Notification Center',
    icon: 'Bell',
    route: '/admin/notifications',
    group: ADMIN_NAV_GROUPS.SYSTEM,
    permission: 'notifications.manage',
    badge: 'Live',
    order: 1410,
    description: 'System alert logs, unread events, and administrative push triggers',
  },
  {
    id: 'notification_rules',
    label: 'Notification Rules',
    icon: 'Sliders',
    route: '/admin/settings/notification-rules',
    group: ADMIN_NAV_GROUPS.SYSTEM,
    permission: 'settings.manage',
    order: 1420,
    description: 'Automated event triggers for low stock, large orders, and new complaints',
  },
  {
    id: 'audit_logs',
    label: 'Security Audit Trail',
    icon: 'ShieldCheck',
    route: '/admin/audit-logs',
    group: ADMIN_NAV_GROUPS.SYSTEM,
    permission: 'audit.view',
    order: 1430,
    description: 'Immutable record of all admin operations, price updates, and permission changes',
  },
  {
    id: 'system_health',
    label: 'System Health & Metrics',
    icon: 'Cpu',
    route: '/admin/system-health',
    group: ADMIN_NAV_GROUPS.SYSTEM,
    permission: 'system.health',
    order: 1440,
    description: 'Database telemetry, queue backlog, cache hit ratio, and server performance',
  },
  {
    id: 'admin_appearance',
    label: 'Admin Theme & Branding',
    icon: 'Palette',
    route: '/admin/settings/appearance',
    group: ADMIN_NAV_GROUPS.SYSTEM,
    permission: 'settings.manage',
    badge: 'Theme',
    order: 1445,
    description: 'Dynamic typography, color palette, logo branding, density, and live appearance preview',
  },
  {
    id: 'general_settings',
    label: 'Store Settings',
    icon: 'Sliders',
    route: '/admin/settings',
    group: ADMIN_NAV_GROUPS.SYSTEM,
    permission: 'settings.manage',
    order: 1450,
    description: 'Store contact info, currency, tax rates, delivery policies, and cache controls',
  },
];

export const ADMIN_GROUP_DEFINITIONS = [
  { key: ADMIN_NAV_GROUPS.OVERVIEW, title: 'Overview', order: 1 },
  { key: ADMIN_NAV_GROUPS.CATALOG, title: 'Catalog', order: 2 },
  { key: ADMIN_NAV_GROUPS.SALES, title: 'Sales', order: 3 },
  { key: ADMIN_NAV_GROUPS.CUSTOMERS, title: 'Customers', order: 4 },
  { key: ADMIN_NAV_GROUPS.INVENTORY, title: 'Inventory', order: 5 },
  { key: ADMIN_NAV_GROUPS.PROMOTIONS, title: 'Pricing & Promotions', order: 6 },
  { key: ADMIN_NAV_GROUPS.MARKETING, title: 'Marketing', order: 7 },
  { key: ADMIN_NAV_GROUPS.STOREFRONT, title: 'Storefront', order: 8 },
  { key: ADMIN_NAV_GROUPS.CX, title: 'Customer Experience', order: 9 },
  { key: ADMIN_NAV_GROUPS.OPERATIONS, title: 'Operations', order: 10 },
  { key: ADMIN_NAV_GROUPS.CCTV, title: 'CCTV Solutions', order: 11 },
  { key: ADMIN_NAV_GROUPS.REPORTING, title: 'Reporting', order: 12 },
  { key: ADMIN_NAV_GROUPS.INTEGRATIONS, title: 'Integrations', order: 13 },
  { key: ADMIN_NAV_GROUPS.SYSTEM, title: 'System', order: 14 },
];
